### ISSUE TITLE
Many non working shortcuts on desktop

### ISSUE THREAD

**Issue by sharicov** [wimbrts/Make_WinPE#1]
Amazing software! Great job, worked as described, very easy to use!
Created large wim from Win11_English_x64v1.iso
Didn't change anything besides setting bootable USB.
After PC boots from the USB there are a lot of non working shortcuts on the Desktop (Explorer-x64, Foxit_Reader etc.).
Could you please give an option, when creating the USB to avoid creating those shortcuts?
Not everyone is using portable programs.
For those who do use portable programs, could you please add additional wizard to automatically integrate it into the wim? Like PortableApps.com application manager?
Thanks again for great project, extremely useful!

**Comment by wimbrts** [comment]
The non-working shortcuts on Desktop can be removed in Add_11_LARGE_EXPL\Users\Default\Desktop or for other versions in Add_Folders_Files\Windows\System32\config\systemprofile\Desktop.
You can also modify Make_WinPE\File_List\Remove_Files_LARGE_EXPL.txt Or e.g. Remove_Files_SMALL.txt to let remove the Desktop Links that you don't want.

If you prefer to have an ISO without Portable Apps than better use [Win10XPE](https://github.com/ChrisRfr/Win10XPE) with [recent version Download](https://github.com/ChrisRfr/Win10XPE/releases)
How do you Boot the ISO ? It is less versatile as compared to PE WIM file that fits excellent in Multi-Boot environment without extraction. You can use PE WIM straight in any Windows Boot Manager Menu and that is Not the case for the ISO file that you are asking for.

See also [VHD_WIMBOOT.pdf](https://github.com/wimbrts/UEFI_MULTI/releases) on How to Multi-Boot

**Comment by sharicov** [comment]
Thanks for the advice, I used Win10XPE in the past, but it's way more
complicated.
Normally booting with ventoy so versatility is not an issue.
Iso provides more flexibility with media, wim needs BCD adjustment each
time I switch USB media, rather than just copying ISO into the ventoy
partition (zero configuration).
