### ISSUE TITLE
Temp folder is full

### ISSUE THREAD

**Issue by sharicov** [wimbrts/Make_WinPE#2]
In the WinPE environment some programs complain about full temp folder.
Is it possible to set it on USB/internal drive? Maybe even automatically in the wim creation wizard?

**Comment by wimbrts** [comment]
Never got your issue with full Temp folder.
Can you specify what programs and conditions give the issue ?

**Comment by sharicov** [comment]
For example windowsdesktop-runtime-3.1.23-win-x64.exe or Microsoft .NET
redistribution.
No special conditions, just running it and getting error messages
(0x80070660 and 0xc0000135)

**Comment by wimbrts** [comment]
I get indeed the same error message.
Strange. 
B:\Temp is in RAMDISK and has sufficient Space.
In 10XPE same B:\Temp is working OK, but Not in my case of PE_19041_US_L.wim

How come ?

**Comment by sharicov** [comment]
Maybe different type of temp used, windows has several:
C:\Users\AppData\Local\Temp and c:\windows\temp
