### ISSUE TITLE
Feature request - create ISO

### ISSUE THREAD

**Issue by sharicov** [wimbrts/Make_WinPE#3]
Is it possible to add an option to create ISO file instead of wim?
Would be very useful for multiboot environment and creating custom ISO distrubutions.

**Comment by wimbrts** [comment]
If you prefer to have an ISO without Portable Apps than better use [Win10XPE](https://github.com/ChrisRfr/Win10XPE) with [recent version Download](https://github.com/ChrisRfr/Win10XPE/releases)
How do you Boot the ISO ? It is less versatile as compared to PE WIM file that fits excellent in Multi-Boot environment without extraction. You can use PE WIM straight in any Windows Boot Manager Menu and that is Not the case for the ISO file that you are asking for.

See also [VHD_WIMBOOT.pdf](https://github.com/wimbrts/UEFI_MULTI/releases) on How to Multi-Boot

**Comment by sharicov** [comment]
Thanks for the advice, I used Win10XPE in the past, but it's way more
complicated.
Normally booting with ventoy so versatility is not an issue.
Iso provides more flexibility with media, wim needs BCD adjustment each
time I switch USB media, rather than just copying ISO into the ventoy
partition (zero configuration).

Another important aspect of using ISO that its content  is read only, which is a good thing for some projects
