### ISSUE TITLE
Drive Y not mapped on boot

### ISSUE THREAD

**Issue by sharicov** [wimbrts/Make_WinPE#4]
Put Drive.y in the root of USB drive, however it's not mapped as drive Y on boot.
Y letter is not taken by other disks, clicking on (Y) Drive link gives "problem with shortcut" message.
As the result there are many unworking shortcuts on the desktop.

**Comment by wimbrts** [comment]
How did you prepare your USB-Drive ?

Your Issue does Not occur in my case ....
![sshot-004](https://user-images.githubusercontent.com/38395846/160640262-c002f201-bf20-490d-9a76-452d9078f052.jpg)
![PE_22000_US_L_2022-03-29_163020](https://user-images.githubusercontent.com/38395846/160640310-dacb1b4f-63c9-4f88-9e98-9256be908f34.jpg)

**Comment by sharicov** [comment]
Starting the whole process and adding screenshots on the go.
Please note I am using same partition for disk Y as WinPE wim partition.
EFI partition 330MB
![image](https://user-images.githubusercontent.com/1933626/160773747-8a18f48a-32ac-41f5-9f96-6a4b72139f7a.png)
![image](https://user-images.githubusercontent.com/1933626/160773796-2305a38a-cc85-45e4-ad09-ba87251a8e1a.png)
![image](https://user-images.githubusercontent.com/1933626/160773816-5d24191d-a4c9-4469-aa01-4d83215022e0.png)
![image](https://user-images.githubusercontent.com/1933626/160773843-139cdc83-1b6d-47b0-a9cb-8b0c8d03339c.png)
Adding wifi drivers (getting error: "couldn't add all drivers" during the build process, but window disappear too fast to capture)
![image](https://user-images.githubusercontent.com/1933626/160774051-fd025151-d8c2-4d5a-ab5e-ca89f01cb480.png)
Adding portable files:
![image](https://user-images.githubusercontent.com/1933626/160774119-ed317e97-82a0-4aab-9eec-06dfb66a2a2a.png)

![image](https://user-images.githubusercontent.com/1933626/160774148-7ab448e7-9616-461c-b248-f8c869b30033.png)

![image](https://user-images.githubusercontent.com/1933626/160774207-0dbefee8-ffd6-4715-85f9-4cff60847bf6.png)

![image](https://user-images.githubusercontent.com/1933626/160774413-8a6b3802-93b1-4ef3-af4b-fd547acbd0d7.png)

Will post in WinPE screenshots once rebooted into it.

**Comment by sharicov** [comment]
![image](https://user-images.githubusercontent.com/1933626/160775573-42692a66-83f7-441d-b051-5cf22a032f09.png)

**Comment by wimbrts** [comment]
Your USB is Removable USB-Stick, whereas my USB is Fixed Portable SSD with two partitions as made by [USB_FORMAT](https://github.com/wimbrts/USB_FORMAT/releases)
That might be the reason that LetterSwap.exe fails to Set Drive.y as Drive Y:
In my case also WinPE folder is located on the Drive containing Drive.y file so that is not the cause oof the problem.
Check the Log file created by LetterSwap.exe in %Temp%\LetterSwap.log
Try with different USB Fixed Device preferably USB Portable SSD and use [USB_FORMAT](https://github.com/wimbrts/USB_FORMAT/releases) to create the two partitions formatted as FAT32 and NTFS.

**Comment by sharicov** [comment]
OK, thanks, will try to check later on.

**Comment by sharicov** [comment]
Checked, working, BTW USB_Format is terrific peace of software.
Thank you very much for the advise!
