### ISSUE TITLE
Generated wim cannot be processed by WinNTSetup

### ISSUE THREAD

**Issue by sharicov** [wimbrts/Make_WinPE#6]
Created wim with latest version using latest win11 iso Win11_23H2_English_x64v2 (all default parameters)

when trying to create vhd using winntsetup (latest) getting error: Error windows pe at source.

Same issue with windows 10 as source

**Comment by wimbrts** [comment]
PE WIM files are Not meant to be installed in VHD and it is normal that WinNTSetup refuses to Install PE .wim files.
The normal way of booting PE WIM files is by loading the PE*.wim file into RAMDISK and then booting with Windows PE.
In Make_WinPE you can Select the Boot Drive and the WinPE Drive and then an entry is made in your BootManager Menu. Booting from Internal SSD Harddisk Or from USB portable SSD with your PE*.wim file is both supported.
Also [UEFI_MULTI](https://github.com/wimbrts/UEFI_MULTI/releases) portable app can be used to make Windows BootManager Menu entries for your PE*.wim files.

**Comment by sharicov** [comment]
Thanks a lot for clarification, then why winntsetup is mentioned on the project forum with screenshot of it with wim as a source, it's very misleading.

**Comment by wimbrts** [comment]
The main purpose of booting with PE*.wim from RAMDISK is to be in environment where you can use WinNTSetup to Install Win 10 / 11 x64 wim files on your internal SSD harddisk partition or in VHD located on NTFS partition.
So you see it is Not misleading at all. The given screenshot is from the PE environment where WinNTSetup is used to Install Windows. Read more about it in the [VHD_Compact PDF](https://github.com/wimbrts/Make_WinPE/releases) Manual.

**Comment by sharicov** [comment]
I see, thanks again!
